### ISSUE TITLE
cmake . -DCMAKE_INSTALL_PREFIX=/usr  

### ISSUE THREAD

**Issue by ibrahimisim** [Wicker25/Rpi-hw#12]
When I run sudo cmake .  I have an error below.

pi@raspberrypi /home/Rpi-hw/examples $ sudo  cmake .
-- Could NOT find Freetype (missing:  FREETYPE_INCLUDE_DIRS)
CMake Error at /usr/share/cmake-2.8/Modules/FindPackageHandleStandardArgs.cmake:97 (MESSAGE):
  Could NOT find Freetype (missing: FREETYPE_INCLUDE_DIRS)
Call Stack (most recent call first):
  /usr/share/cmake-2.8/Modules/FindPackageHandleStandardArgs.cmake:288 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake-2.8/Modules/FindFreetype.cmake:106 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  CMakeLists.txt:17 (find_package)

-- Configuring incomplete, errors occurred!
pi@raspberrypi /home/Rpi-hw/examples $

**Comment by Wicker25** [comment]
Hi @ibrahimisim ,

Do you want to compile the library with the support for FreeType library?
Otherwise you can turn off the support for it by using ```cmake . -DCMAKE_INSTALL_PREFIX=/usr -DUSE_FREETYPE=OFF```

Regards,
Giacomo
